linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/kvql/bunsceal
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: UK
    ignore-words:
      - color   # graphviz attribute name
      - center  # graphviz attribute name
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]
  unparam:
    check-exported: true

linters:
  disable-all: true
  enable:
    # Default linters - keep these for correctness
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Security and correctness linters - keep these
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - goconst
    - gosec
    - makezero
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace

    # Formatting - keep basic formatting
    - gofmt

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gomnd
        - goconst
        - gochecknoglobals
        - maintidx
        - gocyclo
        - funlen
        - gocognit
        - gosec
        - errcheck
        - whitespace
        - govet

    - path: testhelpers/
      linters:
        - errcheck
        - gosec
        - whitespace

    - path: testdata/
      linters:
        - errcheck
        - gocritic
        - gochecknoglobals

    # Relax linting for visualise package (graph rendering code)
    - path: pkg/visualise/
      linters:
        - errcheck
        - whitespace
        - stylecheck
        - staticcheck
        - gosec
        - govet
        - ineffassign
        - wastedassign

    # Relax linting for util package
    - path: pkg/util/
      linters:
        - errcheck
        - gosimple

    # Allow dot imports in test files
    - path: _test\.go
      linters:
        - revive
      text: "dot-imports"

    # Exclude godox (TODO/FIXME comments) for now
    - linters:
        - godox
      text: "Line contains TODO/BUG/FIXME"

    # Exclude specific gosec rules that are too strict
    - linters:
        - gosec
      text: "G304" # File inclusion - we control the paths

    - linters:
        - gosec
      text: "G306" # File permissions in non-test code (for publish.go)

    - linters:
        - gosec
      text: "G301" # Directory permissions

  # Show all issues
  exclude-use-default: false

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  go: '1.22'

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
